### ISSUE TITLE
integration test: Autofix for ScalaTest 3.1.x doesn't work for it:scalafix RewriteDeprecatedNames

### ISSUE THREAD

**Issue by Stefanqn** [scalatest/autofix#21]
Autofix doesn't rewrite ScalaTest code if it's located in `it`

**Comment by scalolli** [comment]
Yeah have the same problem, it doesnt seem to work for it or anything that extends `Test`

**Comment by bjaglin** [comment]
Have a look at https://scalacenter.github.io/scalafix/docs/users/installation.html#integration-tests

**Comment by Stefanqn** [comment]
thank you

**Comment by bjaglin** [comment]
It might be worth updating the READMEs, but considering all open PRs have been open for months, I am not sure when/if this will make it to master.
