### ISSUE TITLE
Scala Version Confusion

### ISSUE THREAD

**Issue by fons** [scalatest/autofix#22]
Hi,

I used autofix to fix some of the scalatest code, but had a hard time with the semantic db portion. 

I commented out the addCompilerPlugin(scalafixSemanticdb) , started up sbt , and ran scalafixEnable from the prompt.

I was using scala version 2.12.11, but it's looking for versions build with 2.12.8 

Just wanted to pass this along just in case it comes up in conversation :)

--------------------------------
Resolving after scalafixEnable
---------------------------------
Resolving jline#jline;2.14.6 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.8!scala-library.jar (277ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.8!scala-reflect.jar (172ms)
[info] downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.8/4.1.4/semanticdb-scalac_2.12.8-4.1.4.jar ...
[info] 	[SUCCESSFUL ] org.scalameta#semanticdb-scalac_2.12.8;4.1.4!semanticdb-scalac_2.12.8.jar (535ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.8!scala-compiler.jar (445ms)
[info] Done updating.
[info] Compiling 32 Scala sources to /Users/fons/Repo/git.hub/MatrixMeta/target/scala-2.12/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.12.8. Compiling...
[info]   Compilation completed in 8.55 s

-----------------------------
Not resolving 
------------------------------
info] Resolving org.fusesource.jansi#jansi;1.12 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalameta#semanticdb-scalac_2.12.11;4.1.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scalameta:semanticdb-scalac_2.12.11:4.1.4 (/Users/fons/Repo/git.hub/MatrixMeta/build.sbt#L63-64)
[warn] 		  +- com.kabouterlabs:matrixmeta_2.12:0.1.0-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.

**Comment by YannMoisan** [comment]
I also run into the same kind of issue :

```
[error] Dependency 'org.scalatest:autofix-3.0.8_2.12:1.0.0'
[error]   not found: /Users/yann.moisan/.ivy2/local/org.scalatest/autofix-3.0.8_2.12/1.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatest/autofix-3.0.8_2.12/1.0.0/autofix-3.0.8_2.12-1.0.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/scalatest/autofix-3.0.8_2.12/1.0.0/autofix-3.0.8_2.12-1.0.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalatest/autofix-3.0.8_2.12/1.0.0/autofix-3.0.8_2.12-1.0.0.pom
```
