### ISSUE TITLE
Consider add GitHub repository topics

### ISSUE THREAD

**Issue by exoego** [scalatest/autofix#9]
It would be helpful if this repository get tagged with topics `scalatest` and `scalafix`, so GitHub users can find this repository on these topics.
![image](https://user-images.githubusercontent.com/127635/62430260-29a08680-b755-11e9-9933-d88d59a5d813.png)

Adding topics is also useful, since Scaladex allow users to [filter Scala dependencies using **GitHub topics**](https://index.scala-lang.org/search?topics=scalafix).
This is often more useful than normal text-based filtering, since text-based filtering is quite noisy.

**Comment by bvenners** [comment]
Thanks for the suggestion. It might also be better if we rename the whole repo something with scalatest in it, like: scalatest-autofix.
